[package]
name = "hello_program"
version = "0.1.0"
edition = "2021"

[dependencies]
hello_core = { path = "../hello_core" }
serde = { workspace = true }
serde_json = { workspace = true }
nssa_core = { workspace = true }

[dev-dependencies]
nssa_core = { workspace = true }
